# Generated by Django 2.2.1 on 2019-05-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karjoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karjoo',
            name='kjmaharat',
            field=models.TextField(verbose_name='مهارتها'),
        ),
        migrations.AlterField(
            model_name='karjoo',
            name='kjphoto',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='عکس '),
        ),
        migrations.AlterField(
            model_name='karjoo',
            name='kjresume',
            field=models.FileField(blank=True, upload_to='resume/', verbose_name='روزمه '),
        ),
    ]
