# Generated by Django 2.2.1 on 2019-06-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karjoo', '0005_auto_20190603_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='karjoo',
            name='kjage',
            field=models.CharField(choices=[('زیر 18 سال ', 'زیر 18 سال '), ('18-22', -4), ('22-28', -6), ('28-32', -4), ('32-35', -3), ('35-40', -5), ('بالای 40', 'بالای 40')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='karjoo',
            name='kjgender',
            field=models.BooleanField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=50, null=True),
        ),
    ]
