# Generated by Django 2.2.1 on 2019-06-13 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karjoo', '0006_auto_20190613_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karjoo',
            name='kjage',
            field=models.CharField(choices=[('زیر 18 سال ', 'زیر 18 سال '), ('18-22', '18-22'), ('22-28', '22-28'), ('28-32', '28-32'), ('32-35', '32-35'), ('35-40', '35-40'), ('بالای 40', 'بالای 40')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='karjoo',
            name='kjgender',
            field=models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='karjoo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری سایت'),
        ),
    ]
