# Generated by Django 2.2.1 on 2019-06-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karjoo', '0007_auto_20190613_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='karjoo',
            name='kjmaghta',
            field=models.CharField(blank=True, choices=[('زیر دیپلم ', 'زیر دیپلم '), ('دیپلم', 'دیپلم'), ('کاردانی', 'کاردانی'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکترا', 'دکترا')], max_length=50, verbose_name='مدرک'),
        ),
        migrations.AlterField(
            model_name='karjoo',
            name='is_registered',
            field=models.BooleanField(default=False, verbose_name='کاربر ثبت شده '),
        ),
        migrations.AlterField(
            model_name='karjoo',
            name='kjage',
            field=models.CharField(choices=[('زیر 18 سال ', 'زیر 18 سال '), ('18-22', '18-22'), ('22-28', '22-28'), ('28-32', '28-32'), ('32-35', '32-35'), ('35-40', '35-40'), ('بالای 40', 'بالای 40')], max_length=50, null=True, verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='karjoo',
            name='kjgender',
            field=models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=50, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='karjoo',
            name='kjtahsilat',
            field=models.TextField(verbose_name='رشته'),
        ),
    ]
