# Generated by Django 2.2.1 on 2019-06-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karjoo', '0008_auto_20190613_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='karjoo',
            name='kjsalary',
            field=models.CharField(choices=[('زیر 600 هزار تومان', 'زیر 600 هزار تومان'), ('بین 600 هزار تا یک میلیون تومان', 'بین 600 هزار تا یک میلیون تومان'), ('یک تا یک و نیم میلیون تومان', 'یک تا یک و نیم میلیون تومان'), ('حقوق اداره کار', 'حقوق اداره کار'), ('یک و نیم تا دو میلیون تومان', 'یک و نیم تا دو میلیون تومان'), ('دو تا سه میلیون تومان', 'دو تا سه میلیون تومان'), ('بالای سه میلیون تومان', 'بالای سه میلیون تومان')], max_length=120, null=True, verbose_name='حقوق درخواستی'),
        ),
        migrations.AlterField(
            model_name='karjoo',
            name='kjmaghta',
            field=models.CharField(blank=True, choices=[('زیر دیپلم ', 'زیر دیپلم '), ('دیپلم', 'دیپلم'), ('کاردانی', 'کاردانی'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکترا', 'دکترا')], max_length=50, verbose_name='آخرین مدرک'),
        ),
    ]
