# Generated by Django 2.2.2 on 2019-06-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karjoo', '0009_auto_20190613_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karjoo',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='ایمیل'),
        ),
    ]
