# Generated by Django 2.2.2 on 2019-06-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karjoo', '0011_auto_20190614_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karjoo',
            name='kjgender',
            field=models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=50, null=True, verbose_name='جنسیت'),
        ),
    ]
