# Generated by Django 2.2.2 on 2019-06-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karjoo', '0013_karjoo_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karjoo',
            name='transaction',
            field=models.CharField(default=0, max_length=50, verbose_name='شماره تراکنش'),
        ),
    ]
