# Generated by Django 2.2.2 on 2019-06-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karjoo', '0014_auto_20190618_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karjoo',
            name='kjtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
