# Generated by Django 2.2.2 on 2019-06-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karjoo', '0016_auto_20190620_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karjoo',
            name='kjmaghta',
            field=models.CharField(blank=True, choices=[('زیر دیپلم', 'زیر دیپلم'), ('دیپلم', 'دیپلم'), ('کاردانی', 'کاردانی'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکترا', 'دکترا')], max_length=50, null=True, verbose_name='مدرک دانشگاهی'),
        ),
        migrations.AlterField(
            model_name='karjoo',
            name='kjtahsilat',
            field=models.TextField(blank=True, null=True, verbose_name='رشته دانشگاهی'),
        ),
    ]
