# Generated by Django 2.2.1 on 2019-05-29 13:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان شغل')),
                ('job_skills', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None), size=None, verbose_name='مهارتهای مورد نیاز')),
                ('job_salary', models.CharField(max_length=200, verbose_name='حقوق')),
                ('job_limits', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None), size=None, verbose_name='محدودیتهای شغل')),
                ('is_valid', models.BooleanField(default=True, verbose_name='معتبراست')),
            ],
            options={
                'verbose_name': 'شغل',
                'verbose_name_plural': 'شغل ها',
            },
        ),
        migrations.CreateModel(
            name='Karfarma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kfcname', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('kfmname', models.CharField(max_length=200, verbose_name='نام نماینده شرکت')),
                ('domain', models.CharField(max_length=200, verbose_name='فیلد کاری')),
                ('address', models.CharField(max_length=500, verbose_name='آدرس')),
                ('kfmobile', models.CharField(max_length=200, verbose_name='شماره تماس')),
                ('is_registered', models.BooleanField(default=False, verbose_name='ثبت شرکت')),
                ('kfphoto', models.ImageField(blank=True, upload_to='logo/', verbose_name='لوگو')),
                ('kfrtime', models.DateTimeField(auto_now=True)),
                ('job_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='karfarma.Job', verbose_name='فرصت شغلی')),
            ],
            options={
                'verbose_name': 'کارفرما',
                'verbose_name_plural': 'کارفرمایان',
            },
        ),
    ]
