# Generated by Django 2.2.1 on 2019-05-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karfarma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_limits',
            field=models.TextField(verbose_name='محدودیت های شغل'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_skills',
            field=models.TextField(verbose_name='مهارت های مورد نیاز'),
        ),
    ]
