# Generated by Django 2.2.1 on 2019-05-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karfarma', '0002_auto_20190530_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_salary',
            field=models.IntegerField(max_length=200, verbose_name='حقوق'),
        ),
    ]
