# Generated by Django 2.2.1 on 2019-05-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karfarma', '0003_auto_20190530_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_salary',
            field=models.IntegerField(default=0, verbose_name='حقوق'),
        ),
    ]
