# Generated by Django 2.2.1 on 2019-06-03 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karfarma', '0007_karfarma_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karfarma',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری سایت'),
        ),
    ]
