# Generated by Django 2.2.1 on 2019-06-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karfarma', '0008_auto_20190603_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_age_limit',
            field=models.CharField(choices=[('زیر 18 سال ', 'زیر 18 سال '), ('18-22', '18-22'), ('22-28', '22-28'), ('28-32', '28-32'), ('32-35', '32-35'), ('35-40', '35-40'), ('بالای 40', 'بالای 40')], max_length=50, null=True, verbose_name='سن'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_degree_limit',
            field=models.CharField(choices=[('زیر دیپلم ', 'زیر دیپلم '), ('دیپلم', 'دیپلم'), ('کاردانی', 'کاردانی'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکترا', 'دکترا')], max_length=100, null=True, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_gender_limit',
            field=models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن'), ('فرقی ندارد', 'فرقی ندارد')], max_length=50, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_salary',
            field=models.CharField(choices=[('زیر 600 هزار تومان', 'زیر 600 هزار تومان'), ('بین 600 هزار تا یک میلیون تومان', 'بین 600 هزار تا یک میلیون تومان'), ('یک تا یک و نیم میلیون تومان', 'یک تا یک و نیم میلیون تومان'), ('حقوق اداره کار', 'حقوق اداره کار'), ('یک و نیم تا دو میلیون تومان', 'یک و نیم تا دو میلیون تومان'), ('دو تا سه میلیون تومان', 'دو تا سه میلیون تومان'), ('بالای سه میلیون تومان', 'بالای سه میلیون تومان')], max_length=200, null=True, verbose_name='حقوق'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('پاره وقت', 'پاره وقت'), ('تمام وقت', 'تمام وقت'), ('پروژه ای', 'پروژه ای')], max_length=100, null=True, verbose_name='نوع شغل'),
        ),
    ]
