# Generated by Django 2.2.1 on 2019-06-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karfarma', '0009_auto_20190613_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.CharField(choices=[('آموزشی و فرهنگی و هنری ', 'آموزشی و فرهنگی و هنری '), (' اداری و مالی', ' اداری و مالی'), (' بهداشتی و درمانی', ' بهداشتی و درمانی'), ('خدمات', 'خدمات'), ('کشاورزی و محیط زیست', 'کشاورزی و محیط زیست'), ('فنی و مهندسی', 'فنی و مهندسی'), ('فرآوری داده ها ', 'فرآوری داده ها ')], max_length=200, null=True, verbose_name='دسته ی شغلی'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_title2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان دوم شغل'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_title3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان سوم شغل'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان اول شغل'),
        ),
    ]
