# Generated by Django 2.2.2 on 2019-06-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karfarma', '0010_auto_20190613_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_age_limit',
            field=models.CharField(blank=True, choices=[('زیر 18 سال ', 'زیر 18 سال '), ('18-22', '18-22'), ('22-28', '22-28'), ('28-32', '28-32'), ('32-35', '32-35'), ('35-40', '35-40'), ('بالای 40', 'بالای 40')], max_length=50, null=True, verbose_name='سن'),
        ),
    ]
