# Generated by Django 2.2.2 on 2019-06-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karfarma', '0011_auto_20190614_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_category',
            field=models.CharField(blank=True, choices=[('آموزشی و فرهنگی و هنری ', 'آموزشی و فرهنگی و هنری '), (' اداری و مالی', ' اداری و مالی'), (' بهداشتی و درمانی', ' بهداشتی و درمانی'), ('خدمات', 'خدمات'), ('کشاورزی و محیط زیست', 'کشاورزی و محیط زیست'), ('فنی و مهندسی', 'فنی و مهندسی'), ('فرآوری داده ها ', 'فرآوری داده ها ')], max_length=200, null=True, verbose_name='دسته ی شغلی'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_degree_limit',
            field=models.CharField(blank=True, choices=[('زیر دیپلم ', 'زیر دیپلم '), ('دیپلم', 'دیپلم'), ('کاردانی', 'کاردانی'), ('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('دکترا', 'دکترا')], max_length=100, null=True, verbose_name='مدرک تحصیلی'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_gender_limit',
            field=models.CharField(blank=True, choices=[('مرد', 'مرد'), ('زن', 'زن'), ('فرقی ندارد', 'فرقی ندارد')], max_length=50, null=True, verbose_name='جنسیت'),
        ),
    ]
