# Generated by Django 2.2.2 on 2019-06-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karfarma', '0012_auto_20190615_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_gender_limit',
            field=models.CharField(blank=True, choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=50, null=True, verbose_name='جنسیت'),
        ),
    ]
