# Generated by Django 2.2.2 on 2019-06-18 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karfarma', '0013_auto_20190617_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karfarma',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری سایت'),
        ),
    ]
