# Generated by Django 2.2.2 on 2019-06-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karfarma', '0014_auto_20190618_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_work_record',
            field=models.CharField(choices=[('فاقد سابقه ', 'فاقد سابقه'), ('کمتر از یک سال', 'کمتر از یک سال'), ('یک تا سه سال', 'یک تا سه سال'), ('سه تا پنج سال', 'سه تا پنج سال'), ('بالاتر از پنج سال', 'بالاتر از پنج سال')], max_length=50, null=True, verbose_name='سابقه کاری'),
        ),
    ]
